runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /templates
  static_dir: templates
- url: /images
  static_dir: images
- url: /.*
  script: main.app
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.2"


application: userapp
version: 1
runtime: python27
api_version: 1
threadsafe: yes

- url: .*
  script: main.app
