runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /triviacss
  static_dir: triviacss
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
