application: userapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /templates
  static_dir: templates
- url: /stylesheet
  static_dir: stylesheet
- url: /images
  static_dir: images
- url: /.*
  script: brainquizmain.app
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
